export const countries = [
  // Primary markets
  { name: "US", code: "+1" },
  { name: "UK", code: "+44" },
  { name: "Canada", code: "+1" },
  { name: "Australia", code: "+61" },
  { name: "UAE", code: "+971" },
  { name: "Singapore", code: "+65" },
  
  // Europe
  { name: "Austria", code: "+43" },
  { name: "Belgium", code: "+32" },
  { name: "Bulgaria", code: "+359" },
  { name: "Croatia", code: "+385" },
  { name: "Czech Republic", code: "+420" },
  { name: "Denmark", code: "+45" },
  { name: "Finland", code: "+358" },
  { name: "France", code: "+33" },
  { name: "Germany", code: "+49" },
  { name: "Greece", code: "+30" },
  { name: "Hungary", code: "+36" },
  { name: "Ireland", code: "+353" },
  { name: "Italy", code: "+39" },
  { name: "Luxembourg", code: "+352" },
  { name: "Netherlands", code: "+31" },
  { name: "Norway", code: "+47" },
  { name: "Poland", code: "+48" },
  { name: "Portugal", code: "+351" },
  { name: "Romania", code: "+40" },
  { name: "Slovakia", code: "+421" },
  { name: "Slovenia", code: "+386" },
  { name: "Spain", code: "+34" },
  { name: "Sweden", code: "+46" },
  { name: "Switzerland", code: "+41" },
  
  // Middle East & Africa
  { name: "Bahrain", code: "+973" },
  { name: "Egypt", code: "+20" },
  { name: "Israel", code: "+972" },
  { name: "Kenya", code: "+254" },
  { name: "Kuwait", code: "+965" },
  { name: "Morocco", code: "+212" },
  { name: "Nigeria", code: "+234" },
  { name: "Oman", code: "+968" },
  { name: "Qatar", code: "+974" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "South Africa", code: "+27" },
  { name: "Turkey", code: "+90" },
  
  // Asia & Pacific
  { name: "Bangladesh", code: "+880" },
  { name: "Hong Kong", code: "+852" },
  { name: "Indonesia", code: "+62" },
  { name: "Japan", code: "+81" },
  { name: "Malaysia", code: "+60" },
  { name: "New Zealand", code: "+64" },
  { name: "Nepal", code: "+977" },
  { name: "Pakistan", code: "+92" },
  { name: "Philippines", code: "+63" },
  { name: "South Korea", code: "+82" },
  { name: "Sri Lanka", code: "+94" },
  { name: "Taiwan", code: "+886" },
  { name: "Thailand", code: "+66" },
  { name: "Vietnam", code: "+84" },
  
  // Americas
  { name: "Argentina", code: "+54" },
  { name: "Brazil", code: "+55" },
  { name: "Chile", code: "+56" },
  { name: "Colombia", code: "+57" },
  { name: "Mexico", code: "+52" },
  { name: "Peru", code: "+51" }
];
